version: '3.8'

services:
    postgres:
      image: postgres:13
      restart: always
      environment:
      - POSTGRES_DB=${PGNAME}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      ports:
            - ${PGPORT}:5432
      volumes:
      - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
      - 5050:80
      depends_on :
      - postgres
